[phases.setup]
nixPkgs = ["nodejs-22_x"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = [
    "yarn build",
    "mkdir -p ${RAILWAY_VOLUME_MOUNT_PATH:-.data}",
    "yarn seed"
]

[start]
cmd = "node dist/index.js"
